version: "3.9"

services:
  vnc-browser:
    container_name: vnc-browser
    image: systemcube/edge:latest
    ports:
      - "5900:5900"
      - "6080:6080"
    environment:
      VNC_PASSWORD: "edgeadmin"
    restart: unless-stopped
